# 数据库
REDIS_HOST = ''
REDIS_PORT = 6379
REDIS_PWD = '123456'
REDIS_DB = 7

MONGO_HOST = ''
MONGO_PORT = 27017
MONGO_DB = 'tax'
MONGO_USERNAME = 'root'
MONGO_PASSWORD = '123456'
MONGO_AUTHSOURCE = 'admin'
MONGO_AUTHMECHANISM = 'SCRAM-SHA-1'


PUPPETEER_CHROMIUM_PATH = '/usr/bin/chromium-browser'
ELK_HOST = ''
ELK_PORT = '9200'
ELK_INDEX = 'tax'
ELK_USR = ''
ELK_PWD = ''